Add new remediation strategy - pod and volumeattachments deletion
medik8s/poison-pill pull request #110
Opened 2021-11-09 07:53 UTC by n1r1

This is addressing https://github.com/medik8s/poison-pill/issues/103

This PR adds a new remediation strategy to the PPR/PPRT, allowing the user to decide which remediation strategy will be used. By default, we're still going with Node deletion.

The new mode - ResourcesDeletion, has some advantages comparing to node deletion:

1. it should be faster to recover workloads as we directly remove the pods/vas, instead of deleting the node and waiting for some other controller to realize that the pods on that node were deleted.
2. it's less likely to create issues with other 3rd parties, which doesn't take into account the possibility of node being deleted and restored. For example, this will allow OVN users to run poison pill.

2021-11-10 02:22 UTC, beekhof commented on bundle/manifests/poison-pill.medik8s.io_poisonpillremediations.yaml
> +                - ResourcesDeletion
Singular for consistency

```suggestion
                - ResourceDeletion
```

2021-11-10 02:41 UTC, beekhof commented on bundle/manifests/poison-pill.medik8s.io_poisonpillremediationtemplates.yaml
> +                        - ResourcesDeletion
```suggestion
                        - ResourceDeletion
```

2021-11-10 02:41 UTC, beekhof commented on controllers/poisonpillremediation_controller.go
> +
Feels like some/all/much of this could be common to both code paths and better located in `Reconcile()`. No?

2021-11-10 02:41 UTC, beekhof commented on controllers/poisonpillremediation_controller.go
> +	}
Should this happen before you mark it as unschedulable?

2021-11-10 02:41 UTC, beekhof commented on controllers/poisonpillremediation_controller.go
> +	}
What is the risk if this fails?  Will it not look like the node still needs to be fenced at line 172 since the node is no longer unschedulable?

`if !node.Spec.Unschedulable || !utils.TaintExists(node.Spec.Taints, NodeUnschedulableTaint) {`

2021-11-10 07:21 UTC, n1r1 commented on bundle/manifests/poison-pill.medik8s.io_poisonpillremediations.yaml
> +                - ResourcesDeletion
I was wondering about that.
we delete a single node, but multiple resources (pods and volume).
would you still think that the singular form is better?

2021-11-10 07:31 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +
that's a good point but I don't think it possible without over-engineering this.
I thought to create an interface for remediation strategy and to implement the strategy-specific code there, and the reconcile will have the common flow and just call the interface methods (e.g. pre-remediation, fence, post-remediation)

However, if you look closely you'll see that there are subtle differences between the two, and no one guarantees that a future remediation strategy will need the same steps, so I preferred to extract all common code into functions, and duplicate most of the function calls.
In addition, if we'll have a common code for both, we would need to consider how each code change affects both which might be more error prone.

Here's an example for a difference between the two:
NodeDeletion cares about node being deleted, as it's a valid part of the flow:
```
	node, err := r.getNodeFromPpr(ppr)
	if err != nil {
		if apiErrors.IsNotFound(err) {
			//as part of the remediation flow, we delete the node, and then we need to restore it
			return r.handleDeletedNode(ppr)
		}
		r.logger.Error(err, "failed to get node", "node name", ppr.Name)
		return ctrl.Result{}, err
	}
```

However, in ResourcesDeletion, node is not expected to be deleted at all, so it would be an error:

```
	node, err := r.getNodeFromPpr(ppr)
	if err != nil {
		r.logger.Error(err, "failed to get node", "node name", ppr.Name)
		return ctrl.Result{}, err
	}
```

2021-11-10 07:32 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +	}
That's what we did so far in node-deletion.
It's a bit safer to do it after marking it unschedulable.

2021-11-10 07:40 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +	}
yeah, I think you're right and this is a bug that needs to be fixed.
in node deletion we don't have this part.
anyway, we need to distinguish between a node that was fenced and is now running and a node that wasn't fenced yet.
In node deletion we use the node's creationTimestamp to detect that this is a new node.
Not sure how to do that here.

2021-11-10 10:22 UTC, slintes reviewed
1st review on the old strategy only, will review the new one in the afternoon, running out of time out :)

2021-11-10 10:22 UTC, slintes commented on controllers/poisonpillremediation_controller.go
> +	case "NodeDeletion":
I think these values should be constants in the api package

2021-11-10 10:22 UTC, slintes commented on controllers/poisonpillremediation_controller.go
> +		return ctrl.Result{RequeueAfter: 10 * time.Second}, nil
in the old version we don't requeue, is the change on purpose?

2021-11-10 10:22 UTC, slintes commented on controllers/poisonpillremediation_controller.go
> +	if r.MyNodeName == node.Name {
Oh, interesting, in the old version we waited for TimeAssumedRebooted for no reason, right?

2021-11-10 10:22 UTC, slintes commented on controllers/poisonpillremediation_controller.go
> +// if not, it will also return the remaining time for that to happen
nit: I understand there are no rules for having a space after `//` or not, but mixing it looks strange. Personnaly I prefer with space, but I'm fine without.

2021-11-10 10:42 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +	case "NodeDeletion":
definitely. thanks

2021-11-10 10:45 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +	if r.MyNodeName == node.Name {
no, we didn't wait :)
we rebooted instantly. it's a bit confusing.

2021-11-10 14:16 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +	if r.MyNodeName == node.Name {
the difference is that previously we would reboot only if the time to assume that node has been rebooted didn't pass.
Now we will reboot as long as the PPR still exists (and poison pill is running on the unhealthy node)

2021-11-10 14:39 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +		return ctrl.Result{RequeueAfter: 10 * time.Second}, nil
The change is on purpose and mainly comes from the code refactoring, not from a real need.
do you see any problem with this?

2021-11-10 17:19 UTC, slintes reviewed
some nits, but otherwise the code looks good to me so far

2021-11-10 17:19 UTC, slintes commented on controllers/poisonpillremediation_controller.go
> +			GracePeriodSeconds: &zero,
maybe a bit nicer:
```
import "k8s.io/utils/pointer"
...
GracePeriodSeconds: pointer.Int64Ptr(0),
```

2021-11-10 17:19 UTC, slintes commented on controllers/poisonpillremediation_controller.go
> +	volumeattachments := storagev1.VolumeAttachmentList{}
- uppercase A in `volumeAttachments`
- for consistency maybe make this a pointer, like with the pod above?

2021-11-10 17:19 UTC, slintes commented on controllers/poisonpillremediation_controller.go
> +	}
> Not sure how to do that here

Introduce a new phase `node fenced`, only mark the node schedulable when that phase was successfully set, and check that phase in line 172?
(on a side note: conditions are preferred over phase, but that's another story :) )

2021-11-10 17:21 UTC, slintes commented on controllers/poisonpillremediation_controller.go
> +	if r.MyNodeName == node.Name {
ah yes, I misread the time check 😎

2021-11-11 08:07 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +
sure, thanks :)

2021-11-14 15:22 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +		r.logger.Info("waiting for unschedulable taint to appear", "node name", node.Name)
yeah I agree...
not sure how to resolve this without over complicating stuff or double checking

2021-11-14 15:23 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +
fixed

2021-11-14 15:24 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +// if not, it will also return the remaining time for that to happen
fixed

2021-11-14 15:24 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +	"k8s.io/apimachinery/pkg/fields"
fixed

2021-11-14 15:24 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +	case "NodeDeletion":
fixed

2021-11-14 15:25 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +	volumeattachments := storagev1.VolumeAttachmentList{}
fixed

2021-11-14 15:27 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +		return ctrl.Result{RequeueAfter: 10 * time.Second}, nil
yes, I'm not sure which way is better, I'll revert to the previous implementation where we just ignore it

2021-11-14 15:27 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +		return ctrl.Result{RequeueAfter: 10 * time.Second}, nil
just to make sure we're aligned - the "endless loop" is a reconcile once in 10 seconds.

2021-11-14 15:28 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +		return ctrl.Result{RequeueAfter: 10 * time.Second}, nil
I think I'll return an error to use exponential backoff.

2021-11-15 14:30 UTC, n1r1 commented
/retest

2021-11-20 11:34 UTC, slintes commented on controllers/poisonpillremediation_controller.go
> +		return ctrl.Result{RequeueAfter: 10 * time.Second}, nil
> the "endless loop" is a reconcile once in 10 seconds until PPR gets deleted

yes

>  I'll return an error to use exponential backoff

👍🏼

2021-11-20 11:41 UTC, slintes commented
Code wise this looks good to me now, but I didn't test it.
Talking about tests: do you plan to add unit or e2e tests for this?

2021-11-22 07:21 UTC, n1r1 commented
> Talking about tests: do you plan to add unit or e2e tests for this?

absolutely. see my first comment in this PR, specifically:

> Tests will be added in a follow up PR, to avoid making this one too big

FWIW I manually tested this for now.

2021-11-22 07:41 UTC, slintes commented
> > Talking about tests: do you plan to add unit or e2e tests for this?
> 
> absolutely. see my first comment in this PR, specifically:
> 
> > Tests will be added in a follow up PR, to avoid making this one too big
> 
> FWIW I manually tested this for now.

Ah, sorry, missed that.
/lgtm

Because of the `ResourcesDeletion` vs `ResourceDeletion` discussion, which seems unresolved, I'll put a hold on it. (I have no strong preference here, I would probably take `Resource`, but just because it's shorter 😉  ) 
/hold

2021-11-22 14:43 UTC, n1r1 commented on bundle/manifests/poison-pill.medik8s.io_poisonpillremediations.yaml
> +                - ResourcesDeletion
fixed

2021-11-22 16:14 UTC, slintes commented on controllers/poisonpillremediation_controller.go
> +	}
oh, I almost missed this one, I think it should be addressed?

2021-11-22 16:15 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +	}
yep

2021-11-23 15:44 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +	}
@slintes I believe 5147a1bb106ebf33955bc8bd4500ae84508d9299 fixes this, could you please review?

2021-11-23 17:23 UTC, n1r1 commented
/retest

2021-11-23 19:34 UTC, n1r1 commented
/retest

2021-11-24 13:01 UTC, slintes commented on controllers/poisonpillremediation_controller.go
> +	}
I think that commit is shifting the issue to another place now: when the status update fails, the node can be rebooted again in line 192 by a fresh PP agent pod on the affected node? We also delete VAs and pods again, but that isn't an issue IMHO.

Thinking this further: don't we always have a race here, also when the status update works? Quick reboot and new PP pod starting, versus slow VA / pod deletion and status update?

2021-11-24 13:04 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +	}
new PP pod will be placed on the unhealthy node only after we removed the unschedulable taint, so I think we don't have an issue here, as we remove it AFTER the ppr status was updated.

2021-11-24 13:18 UTC, slintes commented on controllers/poisonpillremediation_controller.go
> +	}
are you sure?
"The default scheduler ignores unschedulable Nodes when scheduling daemon set pods."
https://docs.openshift.com/container-platform/4.9/nodes/jobs/nodes-pods-daemonsets.html

2021-11-24 13:50 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +	}
> "The default scheduler ignores unschedulable Nodes when scheduling daemon set pods."
I find this statement very confusing :) if a scheduler ignores unschedulable Nodes when scheduling, it sounds like it won't use these nodes when scheduling.

anyway, it looks like you're right. I tried to mark a node as unshcuedlable and delete its poison pill pod, and I saw it was recreated immediately. 

we always assume this is not the case, and I wonder why we didn't see multiple reboots for the same host so far :thinking:

2021-11-24 14:07 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +	}
just to clarify - this potentially impacts also the node deletion scenario we use today.
Maybe this can be avoided by checking the uptime of the machine. if uptime > ppr.CreationTimestamp, no reboot is required

2021-11-24 14:16 UTC, slintes commented on controllers/poisonpillremediation_controller.go
> +	}
> I find this statement very confusing :) 

ha, now when you say it, I agree 🙂 

> this potentially impacts also the node deletion scenario

I think the `node.CreationTimestamp.After(ppr.CreationTimestamp.Time)` check prevents it there

2021-11-24 14:20 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +	}
indeed, but the poison pill pod could come up even before the node was deleted.
we wait ~3 minutes. if the node has completed reboot by then, it could reboot itself again

2021-11-25 09:09 UTC, n1r1 commented
/retest

2021-11-25 10:28 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +	}
@slintes 
I've added uptime check in 04816127a83cae7a28c9face58b1e1c2e80968c6.
WDYT?

2021-11-25 14:05 UTC, slintes requested changes
Good idea with checking uptime. One comment about the used package though, otherwise lgtm

2021-11-25 14:05 UTC, slintes commented on pkg/utils/uptime.go
> +	"syscall"
this package is deprecated, please use `golang.org/x/sys/unix`, see https://pkg.go.dev/syscall

2021-11-25 14:17 UTC, n1r1 commented on pkg/utils/uptime.go
> +	"syscall"
right. good catch. fixed

2021-11-26 09:58 UTC, slintes approved these changes
/lgtm

2021-11-26 12:19 UTC, n1r1 commented
/unhold

2021-11-26 12:19 UTC, merged

2021-12-07 13:27 UTC, dyasny commented
Having two strategies is nice but why make it an OR? In classic fencing we have multiple tiers, if one fails we try the next one

2021-12-07 13:33 UTC, n1r1 commented
In the two modes the node is being fenced by the same way - reboot.
Remediation strategy is basically just the way to signal kubernetes that the node was fenced and it's safe to reschedule the workloads elsewhere.

What would be the benefit to delete the node after the pods and VAs already deleted?

2021-12-07 13:40 UTC, slintes commented
> multiple tiers, if one fails we try the next one

We have something like this in the backlog of NodeHealthCheck, there we could trigger PP with different strategies (which doesn't make much sense as Nir explained), or even completely different remediators

2021-12-07 14:41 UTC, dyasny commented
> What would be the benefit to delete the node after the pods and VAs already deleted?

When tackling this issue, I wrote a very basic script that monitored the status of the nodes and if one was NotReady or Down for longer than 60 seconds, it would try to delete the volumeAttachments on it, so that the workloads would be able to reschedule. Which didn't work (every time). Looking in a bit deeper, I saw that VAs get restored faster than a newly scheduled workload takes over the volume in some cases. And as the remediation loop grows longer, the harder it is for the workload to reschedule. In this case, deleting the node helped reset the state of things. 

I didn't investigate too deeply into why this happened on some setups and didn't on others (I was running with multiple k8s distros - k3s, basic kubeadm, kops, eks, aks, microk8s and multiple versions of each).

2021-12-07 15:15 UTC, n1r1 commented
> it would try to delete the volumeAttachments on it

did it also try to delete the pods on the unhealthy node? if yes, which resource was deleted first? va or pod?

>  I saw that VAs get restored faster than a newly scheduled workload takes over the volume in some cases

I'm not sure how node deletion fixes this.