Refactor watchdog
medik8s/poison-pill pull request #14
Opened 2021-05-10 08:22 UTC by slintes

- run feeding in its own loop
- let the manager handler the lifecycle: call start, disarm using context
- deduplicate code by integrating the fake watchdog into the linux watchdog

also moved all packages except controllers (would break code generation) to `/pkg`

2021-05-12 10:32 UTC, n1r1 requested changes

2021-05-12 10:32 UTC, n1r1 commented on pkg/watchdog/watchdog.go
> +			wd.log.Error(err, "failed to feed watchdog!")
this part is not protected by the mutex. Is the logger thread-safe?

2021-05-12 10:32 UTC, n1r1 commented on pkg/watchdog/watchdog.go
> +		if err := wd.disarm(); err != nil {
there could be a race here.
Looks like the feeding is not protected by the mutex, so it could run in parallel.
So once this writes the disarm character, the feeding might re-arm the watchdog (it could happen befor disarm() closes the fd)

2021-05-12 10:32 UTC, n1r1 commented on pkg/watchdog/watchdog.go
> +func New(log logr.Logger) (Watchdog, error) {
WDYT about making this a singletone?

2021-05-12 10:32 UTC, n1r1 commented on pkg/watchdog/watchdog.go
> +func NewFake(log logr.Logger) (Watchdog, error) {
Not a big thing, but personally I prefer to use dependency injection for tests rather than adding test code to production code.

what's your take on this?

2021-05-12 17:22 UTC, slintes commented on pkg/watchdog/watchdog.go
> +	wd.start()
oh yes, thanks. Question though: should we handle this as "ok, we go on with soft reboot", or a serious problem which stops the pod? So just log the problem and don't mark the watchdog as started? Or return an error? 🤔

2021-05-12 17:25 UTC, slintes commented on pkg/watchdog/watchdog.go
> +			wd.log.Error(err, "failed to feed watchdog!")
hm, good question. I never saw a logger being protected at least. And the worst thing which can happen is logs being in wrong order, right? So I think this is fine.

2021-05-12 17:48 UTC, slintes commented on pkg/watchdog/watchdog.go
> +		if err := wd.disarm(); err != nil {
good catch, improved the lock

2021-05-12 18:06 UTC, slintes commented on pkg/watchdog/watchdog.go
> +func New(log logr.Logger) (Watchdog, error) {
I always hesitate to use singletons because they are often referred to as anti pattern and not pattern.
What would be the advantage here?

See e.g. https://www.michaelsafyan.com/tech/design/patterns/singleton

2021-05-12 18:09 UTC, slintes commented on pkg/watchdog/watchdog.go
> +func NewFake(log logr.Logger) (Watchdog, error) {
The idea was to prevent too much code duplication while keeping same (or at least very similar) behavior for start / stop / feed etc. I was changing code at 2 places all the time. Do have an example for how dependency injection would look like?

2021-05-12 18:31 UTC, slintes commented
addressed feedback, rebased, move render / apply to pkg

2021-05-13 13:41 UTC, n1r1 commented on pkg/watchdog/watchdog.go
> +func New(log logr.Logger) (Watchdog, error) {
When a caller calls `disarm()` it expect it to disarm.
When a caller calls `Stop()` it expect the wd to stop and trigger reboot.

If there are multiple callers which started multiple watchdogs, the would interfere one with each other and will break the expectations I mentioned above, as one might feed the watchdog, after the other stopped it.

2021-05-13 13:54 UTC, n1r1 commented on pkg/watchdog/watchdog.go
> +			wd.log.Error(err, "failed to feed watchdog!")
Worst case can be much worse IMO. e.g. mixed log lines (instead of "hello" and "world" you get "hellworldo") or even corruption.

2021-05-13 13:59 UTC, n1r1 commented on pkg/watchdog/watchdog.go
> +func NewFake(log logr.Logger) (Watchdog, error) {
The previous implementation is kind of dependency injection. 
if we don't want to duplicate some of the code maybe we can embed a linuxWatchdog in the dummyWatchdog, and call only the functions we're interested in, otherwise do the dummy implementation.

2021-05-17 12:04 UTC, slintes commented on pkg/watchdog/watchdog.go
> +			wd.log.Error(err, "failed to feed watchdog!")
ok, this is inside the lock now

2021-05-17 12:05 UTC, slintes commented on pkg/watchdog/watchdog.go
> +func New(log logr.Logger) (Watchdog, error) {
initiating multiple linux watchdogs is prevented now

2021-05-17 12:10 UTC, slintes commented on pkg/watchdog/watchdog.go
> +func NewFake(log logr.Logger) (Watchdog, error) {
ok, I refactored it:
We still have the `Watchdog interface`, providing the public methods.
Then we have a `watchdogImpl` interface now, which provides the internal, implementation specific methods.
Then there is a `synchronizedWatchdog`, which does all the sync stuff on the public methods, and calls the internal methods. The internal methods are implemented by a linux and a fake watchdog, which are provided as dependency to the synchronizedWatchdog.
Does that make sense? :)

2021-05-23 14:17 UTC, n1r1 requested changes
looks good! mostly nits

2021-05-23 14:17 UTC, n1r1 commented on pkg/watchdog/interface.go
> +		if err := swd.impl.feed(); err != nil {
actually this can happen, and this check is very important.
the cancel func doesn't block until the go routine actually stopped

2021-05-23 14:17 UTC, n1r1 commented on pkg/watchdog/interface.go
> +func (swd *synchronizedWatchdog) Stop() {
It worth documenting that Stop() could actually trigger a reboot and to mention explictly it doesn't disarm the watchdog

2021-05-23 14:17 UTC, n1r1 commented on pkg/watchdog/interface.go
> +	return swd.timeout
this should be protected by the mutex

2021-05-23 14:23 UTC, n1r1 commented on pkg/watchdog/watchdog.go
> +	wd.start()
good question. for now, let's just log the problem. 
in the future we should probably add a config value so the user can decide if it wants watchdog or nothing.
if you agree, let's create a ticket in the backlog for this

2021-05-23 14:26 UTC, n1r1 commented on pkg/watchdog/watchdog.go
> +func NewFake(log logr.Logger) (Watchdog, error) {
nicely done!

2021-05-25 13:41 UTC, slintes commented on pkg/watchdog/watchdog.go
> +func NewFake(log logr.Logger) (Watchdog, error) {
thx :)

2021-05-25 13:41 UTC, slintes commented on pkg/watchdog/interface.go
> +type synchronizedWatchdog struct {
done

2021-05-25 13:41 UTC, slintes commented on pkg/watchdog/interface.go
> +	started      bool
done

2021-05-25 13:41 UTC, slintes commented on pkg/watchdog/interface.go
> +	stopped      bool
done

2021-05-25 13:41 UTC, slintes commented on pkg/watchdog/interface.go
> +	swd.mutex.Lock()
I was unsure because it's unlocked and locked again later... but yes, now I agree that doing the deferred unlock here is nicer

2021-05-25 13:42 UTC, slintes commented on pkg/watchdog/interface.go
> +func (swd *synchronizedWatchdog) Stop() {
done (for all methods on the interface)

2021-05-25 13:42 UTC, slintes commented on pkg/watchdog/interface.go
> +	return swd.timeout
👍🏼

2021-05-25 14:20 UTC, n1r1 commented on pkg/watchdog/synchronized.go
> +		return errors.New("watchdog was isStarted more than once. This is likely to be caused by being added to a manager multiple times")
s/isStarted/started :)

2021-05-25 14:20 UTC, n1r1 commented on pkg/watchdog/synchronized.go
> +	swd.log.Info("watchdog isStarted")
same here

2021-05-25 14:21 UTC, n1r1 commented on pkg/watchdog/synchronized.go
> +	// feed until isStopped
s/isStopped/stopped?

2021-05-25 17:14 UTC, slintes commented on pkg/watchdog/synchronized.go
> +		return errors.New("watchdog was isStarted more than once. This is likely to be caused by being added to a manager multiple times")
oh, I should better review refactoring in strings :)

2021-05-25 17:15 UTC, slintes commented on pkg/watchdog/synchronized.go
> +		// this should not happen because the context is cancelled already.. but just in case
so I was curious and did a test: this happens around 15 times in 1 million calls... good enough for a better comment indeed ;)

2021-05-25 19:42 UTC, merged