remove rbac container proxy
medik8s/poison-pill pull request #149
Opened 2022-02-17 13:43 UTC by razo7

Remove redundant rbac proxy container (fix problem in #144 PR).

Signed-off-by: oraz <oraz@redhat.com>

2022-02-17 14:54 UTC, razo7 commented
/retest

2022-02-17 18:44 UTC, mshitrit commented
/retest

2022-02-21 06:34 UTC, razo7 commented
/retest

2022-02-21 09:36 UTC, slintes commented
/hold

And again: look at the diff. It's removing more than just the proxy container!

2022-02-21 09:40 UTC, beekhof commented on bundle/manifests/poison-pill.clusterserviceversion.yaml
> -                  value: quay.io/medik8s/poison-pill-operator:0.1.3
This isn't part of the proxy though. Did you mean to delete it?

2022-02-24 16:46 UTC, razo7 commented on bundle/manifests/poison-pill.clusterserviceversion.yaml
> -                  value: quay.io/medik8s/poison-pill-operator:0.1.3
No, that was a mistake.

2022-02-24 18:35 UTC, slintes requested changes

2022-02-24 18:35 UTC, slintes commented on config/default/manager_auth_proxy_patch.yaml
> -      - name: kube-rbac-proxy
The name of this patch file is manager_auth_proxy_patch, and you remove exactly that now ;)
Please make a new patch file with all changes NOT related to the proxy, disabled this one, and enable the new patch file. The history of this file should show what needs to be in the new patch. It's not your fault, this was done wrong in the past already (adding things not related to the proxy container to this patch). Let's make it right at least now, so we don't run into confusion again in case we want the proxy container back in future.

2022-02-27 09:24 UTC, razo7 commented on config/default/manager_auth_proxy_patch.yaml
> -      - name: kube-rbac-proxy
I have updated that and created two files instead of one, following NMO's motivation in `kustomization.yaml` https://github.com/medik8s/node-maintenance-operator/blob/master/config/default/kustomization.yaml#L31

2022-02-28 19:25 UTC, slintes reviewed
lgtm
/hold cancel

leaving the official lgtm to @mshitrit

2022-02-28 19:25 UTC, slintes approved these changes

2022-02-28 19:26 UTC, slintes commented
that wasn't planned this way (removing the earlier "request changes" = lgtm) 😄

2022-03-01 06:27 UTC, razo7 commented
/retest

2022-03-01 07:09 UTC, mshitrit commented
/lgtm

2022-03-01 07:45 UTC, merged