Introduce separate peers loop
medik8s/poison-pill pull request #15
Opened 2021-05-10 21:28 UTC by slintes

- Move peers update into own loop
- Also move API error handling to peers
- Stop reconciling when nothing can be done anymore
- Some changes to tests to get them working

Heads up, this is based on #14, should be merged first! Marking as draft to prevent merging.
Also some TODOs might need to be addressed before merging.

2021-05-24 13:46 UTC, n1r1 requested changes

2021-05-24 13:46 UTC, n1r1 commented on pkg/peers/peers.go
> +		p.log.Info("Ignoring error, it came too fast after the last one", "error", newError)
s/error/api-server error

2021-05-24 13:46 UTC, n1r1 commented on pkg/peers/peers.go
> +	nodes := *p.getPeers() // de-reference nodes here, so we don't accidentally modify the original list later on
how this doesn't cause a deadlock?
The lock was acquired by updatePeers() which called this function, and now getPeers() is going to acquire the lock again.

2021-05-24 13:46 UTC, n1r1 commented on pkg/peers/peers.go
> +	nodesBatchCount := 5
we wanted the batch size to be 10% of the cluster

2021-05-24 13:46 UTC, n1r1 commented on pkg/peers/peers.go
> +	// unclear status, assume we are unhealthy
It's not unclear status. we reach this point if no one told us we're healthy or not, and we didn't get enough responses to decide if this an api-server failure or ours.

I'm missing here where is the next batch of nodes being asked? we asked 5 nodes, what's next?
what would prevent us to query the same 5 nodes again in the next iteration?

2021-05-26 18:16 UTC, slintes commented on pkg/peers/peers.go
> +func (p *Peers) Reboot() error {
done

2021-05-26 18:16 UTC, slintes commented on pkg/peers/peers.go
> +	if err := p.List(readerCtx, nodes, client.Limit(nrOfPeers), client.MatchingLabelsSelector{Selector: p.peerSelector}); err != nil {
changed

2021-05-26 18:16 UTC, slintes commented on pkg/peers/peers.go
> +		if healthy := p.HandleError(ctx, err); !healthy {
done

2021-05-26 18:17 UTC, slintes commented on pkg/peers/peers.go
> +	p.reset()
changed to resetErrorState

2021-05-26 18:17 UTC, slintes commented on pkg/peers/peers.go
> +func (p *Peers) HandleError(ctx context.Context, newError error) bool {
removed

2021-05-26 18:18 UTC, slintes commented on pkg/peers/peers.go
> +	p.updatePeers(ctx, false)
removed... don't remember why I did it, probably I assumed the loop will start with the wait period instead of calling the function 🤔

2021-05-26 18:20 UTC, slintes commented on pkg/peers/peers.go
> +func (p *Peers) getPeers() *[]v1.Node {
I removed this, made handleError() private (was used by reconciler in an earlier version, no lock needed anymore, problem solved

2021-05-26 18:20 UTC, slintes commented on pkg/peers/peers.go
> +	nodes := *p.getPeers() // de-reference nodes here, so we don't accidentally modify the original list later on
see last comment

2021-05-26 18:20 UTC, slintes commented on pkg/peers/peers.go
> +		p.log.Info("Ignoring error, it came too fast after the last one", "error", newError)
done

2021-05-26 18:21 UTC, slintes commented on pkg/peers/peers.go
> +	nodesBatchCount := 5
as discussed, I start with 2% percent now, increasing to 5 and 10. Not ideal for small clusters though, we need a better solution IMHO

2021-05-26 18:21 UTC, slintes commented on pkg/peers/peers.go
> +	// unclear status, assume we are unhealthy
fixed, works as in the old version now

2021-06-01 08:05 UTC, n1r1 requested changes

2021-06-01 13:55 UTC, n1r1 commented on pkg/peers/peers.go
> +	for i := 0; len(nodesToAsk) > 0; i++ {
actually I realized that later in the review and forgot to delete it.
I believe this could be confusing. WDYT about changing to `while`?

2021-06-02 16:17 UTC, slintes commented on pkg/peers/peers.go
> +func (p *Peers) updatePeers(ctx context.Context, ignoreError bool) {
good catch, there was another caller in an earlier version

2021-06-02 16:18 UTC, slintes commented on pkg/peers/peers.go
> +	defer p.mutex.Unlock()
correct, it is another leftover from earlier version

2021-06-02 16:18 UTC, slintes commented on pkg/peers/peers.go
> +
good point 👍🏼

2021-06-02 16:18 UTC, slintes commented on pkg/peers/peers.go
> +		}
yes

2021-06-02 16:18 UTC, slintes commented on pkg/peers/peers.go
> +	for i := 0; len(nodesToAsk) > 0; i++ {
there is no `while` in go
I added a comment to clarify

2021-06-03 15:51 UTC, n1r1 commented on pkg/peers/peers.go
> +	for i := 0; len(nodesToAsk) > 0; i++ {
forgot about that :)
This is what they suggest:
https://tour.golang.org/flowcontrol/3

but I'm okay with just a comment

2021-06-03 15:55 UTC, n1r1 commented on pkg/peers/peers.go
> +	ignoreNewErrorsFor time.Duration
maybe this can be removed as well now?

2021-06-06 11:20 UTC, n1r1 commented on controllers/controller_test.go
> +		// this triggers a reconcile! It might cause invalid test results...
why do we care if this triggers reconcile?
Without that the tests are going to be very slow (see next step 100s)

2021-06-08 06:48 UTC, slintes commented on controllers/controller_test.go
> +		// this triggers a reconcile! It might cause invalid test results...
I think we want to be sure that a reconcile is triggered because we requeued the PPR in the reconcile func, and not because it's requeued because of the modification.

2021-06-08 06:59 UTC, n1r1 commented on controllers/controller_test.go
> +		// this triggers a reconcile! It might cause invalid test results...
hmm that makes sense, the downside is slow test.
we can change the safe-timeout-to-delte-a-node in tests, but let's do that in a followup PR

2021-06-08 14:58 UTC, n1r1 reviewed
some minor issues and we can merge!

2021-06-08 15:33 UTC, slintes commented on controllers/poisonpillremediation_controller.go
> +	return ctrl.Result{}, nil
What do you mean with "report"? We log that we are restoring the node at the beginning of this method.
I assumed we remove the finalizer when the health checker deletes the PPR, but doing it before is fine as well, done.

2021-06-08 15:33 UTC, slintes commented on pkg/peers/peers.go
> +func (p *Peers) handleError(newError error) bool {
removed

2021-06-08 15:33 UTC, slintes commented on controllers/poisonpillremediation_controller.go
> +			r.logger.Info("failed to restore node, already exists again")
removed

2021-06-08 17:36 UTC, n1r1 commented on controllers/poisonpillremediation_controller.go
> +	return ctrl.Result{}, nil
yes. report = log.
It's correct that this is in the beginning of this method. Yet this would happen [only if ](https://github.com/medik8s/poison-pill/blob/afa52061e1d85acb7f1e8a3aa46f3061a9cd3325/controllers/poisonpillremediation_controller.go#L102) `node.CreationTimestamp.After(ppr.CreationTimestamp.Time)`

we reach this `return` statement after we deleted the node. we're not done yet. we need to [restore the node](https://github.com/medik8s/poison-pill/blob/afa52061e1d85acb7f1e8a3aa46f3061a9cd3325/controllers/poisonpillremediation_controller.go#L96) and later log it's restored and remove the finalizer.

it's a bit confusing, but the code is not ordered chronologically.

2021-06-08 17:37 UTC, merged