Add basic mutation tests integration + update vendoring
medik8s/poison-pill pull request #28
Opened 2021-05-28 07:13 UTC by mshitrit

Signed-off-by: Michael Shitrit <mshitrit@redhat.com>

2021-06-03 06:58 UTC, n1r1 commented
thanks @mshitrit 

what's the reason for all the vendor changes?

2021-06-03 07:09 UTC, mshitrit commented
Most of it is not really related to the PR changes - It just was out of date and I've updated it as part of this PR

2021-06-03 15:13 UTC, n1r1 requested changes

2021-06-03 16:56 UTC, mshitrit commented on Makefile
> +	git restore .
I think it should be safe since it's called after `verify-no-changes` - so it only rolls back changes made to **go.mod** / **go.sum** as a result of fetching the mutation-test package

2021-06-06 06:30 UTC, mshitrit commented on controllers/suite_test.go
> +	Expect(os.Setenv("TEST_ASSET_KUBECTL", "../testbin/bin/kubectl")).To(Succeed())
IIUC by "both functionalities"  you mean `make test` + new possibility of native go test.
At the moment both work (otherwise this PR would have failed the automatic test)

2021-06-06 06:57 UTC, n1r1 commented on controllers/suite_test.go
> +	Expect(os.Setenv("TEST_ASSET_KUBECTL", "../testbin/bin/kubectl")).To(Succeed())
I meant that currently the user can use these env vars to point to a different location (e.g. `TEST_ASSET_KUBE_APISERVER=/foo/bar/api-server`

2021-06-06 08:00 UTC, merged