API check loop
medik8s/poison-pill pull request #32
Opened 2021-06-08 14:41 UTC by slintes

follow up for #15 

/hold

2021-06-13 12:14 UTC, n1r1 requested changes
looks good, left some comments

2021-06-13 12:14 UTC, n1r1 commented on pkg/apicheck/check.go
> +			if apiErrorsResponsesSum > len(c.peers.GetPeers().Items)/2 { //already reached more than 50% of the nodes and all of them returned api error
it would be better to call `GetPeers()` only once, we already do it before this for loop, so we can keep the length of the nodes in a variable declared outside of this for loop scope.
This is better since:
1. GetPeers() is using a lock which could be locked to update the peer so this adds an unperdictable delay here which could impact the time to reboot a node
2. The list of nodes might change during this for loop.

2021-06-14 19:57 UTC, slintes commented on pkg/apicheck/check.go
> +	client := cs.RESTClient()
fixed

2021-06-14 19:57 UTC, slintes commented on pkg/apicheck/check.go
> +		if err != nil || string(result) != "ok" {
fixed

2021-06-14 19:57 UTC, slintes commented on pkg/apicheck/check.go
> +			c.log.Error(err, "failed to check api server")
fixed

2021-06-14 19:59 UTC, slintes commented on pkg/apicheck/check.go
> +	nodesToAsk := c.peers.GetPeers().Items
I changed peers so that the node list is initialized with an empty list

2021-06-14 20:03 UTC, slintes commented on pkg/apicheck/check.go
> +			if apiErrorsResponsesSum > len(c.peers.GetPeers().Items)/2 { //already reached more than 50% of the nodes and all of them returned api error
1. The delay is predictable and small, it's at most 5 seconds (`apiServerTimeout` in peers), and it can happen once in 15 minutes (`peerUpdateInterval` in main)
2. Actually I see this as an advantage, it calculates 50% of the current cluster, not of the cluster 15 minutes ago, in case it updated?

2021-06-15 05:36 UTC, n1r1 commented on pkg/apicheck/check.go
> +	nodesToAsk := c.peers.GetPeers().Items
even better!

2021-06-15 05:40 UTC, n1r1 commented on pkg/apicheck/check.go
> +			if apiErrorsResponsesSum > len(c.peers.GetPeers().Items)/2 { //already reached more than 50% of the nodes and all of them returned api error
1. Agreed
2. hmm we start with `nodesToAsk` which doesn't get updated. e.g. if you have 10 nodes, `len(nodesToAsk)` is 10, and then the cluster grows to 30 nodes, we'll never get to `len(c.peers.GetPeers().Items)/2` which is 15.

2021-06-15 12:18 UTC, slintes commented on pkg/apicheck/check.go
> +			if apiErrorsResponsesSum > len(c.peers.GetPeers().Items)/2 { //already reached more than 50% of the nodes and all of them returned api error
this is tricky...
what about returning a `lastUpdateTime` in `getPeers`, and if it changes, we restart the complete loop? I think that's the cleanest solution without adding too much complexity...?

2021-06-15 12:36 UTC, slintes commented on pkg/apicheck/check.go
> +			if apiErrorsResponsesSum > len(c.peers.GetPeers().Items)/2 { //already reached more than 50% of the nodes and all of them returned api error
hm, that's also not great, there is a little chance then to run into an endless loop in case it doesn't finish within 15 minutes

2021-06-15 12:39 UTC, n1r1 commented on pkg/apicheck/check.go
> +			if apiErrorsResponsesSum > len(c.peers.GetPeers().Items)/2 { //already reached more than 50% of the nodes and all of them returned api error
this is also a problem as it prolongs the remediation time which should be limited with some upper bound.
I don't see a major issue with working with a snapshot of a given time

2021-06-16 08:32 UTC, slintes commented on pkg/apicheck/check.go
> +			if apiErrorsResponsesSum > len(c.peers.GetPeers().Items)/2 { //already reached more than 50% of the nodes and all of them returned api error
yup, using the initial cluster size now

2021-06-16 12:34 UTC, n1r1 commented on pkg/apicheck/check.go
> +				c.log.Error(err, "peers did not confirm that we are unhealthy, ignoring error")
This is not true when we didn't reach the error threshold.

2021-06-16 12:34 UTC, n1r1 commented on pkg/apicheck/check.go
> +				c.log.Error(err, "peers did not confirm that we are unhealthy, ignoring error")
I'm not blocking the PR for this message

2021-06-16 12:34 UTC, merged