auto config cr create
medik8s/poison-pill pull request #33
Opened 2021-06-08 16:26 UTC by rgolangh

- Remove irrelevant comment
- Create a config CR if not already exists

2021-06-09 06:41 UTC, rgolangh reviewed
The commit msg needs rewording

2021-06-13 14:39 UTC, n1r1 requested changes
looks good!
mainly nits below

2021-06-13 14:39 UTC, n1r1 commented on controllers/poisonpillconfig_controller.go
> +		return gerrors.Wrap(err, "unable to get WatchNamespace")
what are the added value of gerrors over the standard error package?

2021-06-13 14:39 UTC, n1r1 commented on controllers/poisonpillconfig_controller.go
> +func NewConfigIfNotExist(c client.Client) error {
I think we agreed to move this out of the controller isn't it?

2021-06-13 14:39 UTC, n1r1 commented on controllers/poisonpillconfig_controller.go
> +			SafeTimeToAssumeNodeRebootedSeconds: 180,
maybe put these two in const?

2021-06-13 14:39 UTC, n1r1 commented on api/v1alpha1/poisonpillconfig_webhook.go
> +var poisonpillconfiglog = logf.Log.WithName("poisonpillconfig-resource")
s/resource/webhook?

2021-06-13 14:39 UTC, n1r1 commented on api/v1alpha1/poisonpillconfig_webhook.go
> +	return nil
maybe also validate the namespace?

2021-06-21 14:19 UTC, rgolangh commented on config/manager/manager.yaml
> +          - name: WATCH_NAMESPACE
Is that name non descriptive enough? This name is used widely and is a pattern mentioned in the operator SDK.

2021-06-21 14:22 UTC, rgolangh commented on controllers/poisonpillconfig_controller.go
> +		return gerrors.Wrap(err, "unable to get WatchNamespace")
its the same package, just that apimachinery errors name is also 'errors'
I'll alias the apimachinery errors to 'apierrors' and 'gerrors' to 'errors'

2021-06-21 14:27 UTC, rgolangh commented on api/v1alpha1/poisonpillconfig_webhook.go
> +var poisonpillconfiglog = logf.Log.WithName("poisonpillconfig-resource")
ack

2021-06-21 14:27 UTC, rgolangh commented on api/v1alpha1/poisonpillconfig_webhook.go
> +	return nil
which validation you had in mind?

2021-06-21 15:15 UTC, n1r1 commented on config/manager/manager.yaml
> +          - name: WATCH_NAMESPACE
Poison pill watches objects in multiple namespaces, not just the one it was deployed in.
not super important if you feel this is the right naming

2021-06-24 07:56 UTC, rgolangh commented on config/manager/manager.yaml
> +          - name: WATCH_NAMESPACE
ack, changing to CONFIG_WATCH_NAMESPACE

2021-06-24 08:01 UTC, rgolangh commented on controllers/poisonpillconfig_controller.go
> +func NewConfigIfNotExist(c client.Client) error {
done

2021-06-24 08:01 UTC, rgolangh commented on controllers/poisonpillconfig_controller.go
> +			SafeTimeToAssumeNodeRebootedSeconds: 180,
done

2021-06-24 09:02 UTC, rgolangh commented on api/v1alpha1/poisonpillconfig_webhook.go
> +	return nil
ack that's a good call

2021-06-24 09:46 UTC, n1r1 commented on api/v1alpha1/webhook_suite_test.go
> +	err = (&PoisonPillConfig{}).SetupWebhookWithManager(mgr)
this doesn't compile, should be `PoisonPillConfigWebhook` instead of `PoisonPillConfig`

2021-06-24 10:22 UTC, rgolangh commented on api/v1alpha1/webhook_suite_test.go
> +	err = (&PoisonPillConfig{}).SetupWebhookWithManager(mgr)
that was premature git push. stand by

2021-06-24 14:27 UTC, rgolangh commented on api/v1alpha1/poisonpillconfig_webhook.go
> +	return nil
there's no easy way to pass the desired namespace to the webhook implementation and the 
webhook validator itself is always the PoisonPillConfig instance itself. 
I suggest we'll continue with what we have and later on we'll figure out a good way to validate that.
Meanwhile since we always create the config if it doesn't exist then we are mostly covered.

2021-06-24 14:28 UTC, rgolangh commented on config/manager/manager.yaml
> +          - name: WATCH_NAMESPACE
changed my mind - DEPLOYED_NAMESPACE

2021-06-27 06:32 UTC, n1r1 approved these changes
nicely done. thanks!

2021-06-27 06:32 UTC, n1r1 commented on config/default/webhookcainjection_patch.yaml
> +    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
We don't use mutation wehbook, can we comment this out?

2021-06-27 06:32 UTC, n1r1 commented on config/default/webhookcainjection_patch.yaml
> +    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
I also see other files with references to mutation wehbook, maybe we can remove them in a follow up pr. I don't want to block this

2021-06-27 06:32 UTC, merged