Add e2e test
medik8s/poison-pill pull request #59
Opened 2021-07-04 22:59 UTC by slintes

Needs some fine tuning (seems to be flaky, revisit timeouts for making tests faster, ...) but in general all usecases should be covered at least.

2021-07-04 23:00 UTC, slintes commented
will add OpenshiftCI config when this is stable and merged.

2021-07-06 06:55 UTC, mshitrit commented on e2e/poison_pill_test.go
> +				time.Sleep(time.Duration(reconnectInterval.Seconds()+10) * time.Second)
I might be misunderstanding the business logic so feel free to disregard if I do :smile: 

(**Nice to have**) might want to use a waitgroup here instead of Sleep.
It can save test time, and make the test more reliable (since we guarantee all off killApiConnection finished executing before continuing)
Here is a code snippet:

```
var wg sync.WaitGroup
for i, _ := range workers.Items {
	worker := workers.Items[i]
	 wg.Add(1)
	go func() {
		defer GinkgoRecover()
		defer wg.Done()
		killApiConnection(&worker, apiIPs, true)
	}()
}
wg.Wait()	
```

2021-07-06 07:07 UTC, n1r1 requested changes
nicely done!
left some comments that might help to cut flakes

2021-07-06 07:07 UTC, n1r1 commented on e2e/poison_pill_test.go
> +						killApiConnection(&worker, apiIPs, true)
if this is blocking until we reach `reconnectInterval+nodeExecTimeout` it means that when we'll get to block the second worker, the connection would be restored for the first one, so always one of hem (at least) has api connectivity.

2021-07-06 07:07 UTC, n1r1 commented on e2e/poison_pill_test.go
> +				checkPPLogs(node, []string{"failed to check api server", "nodes couldn't access the api-server"})
let's run this checks on the other worker as well

2021-07-06 07:14 UTC, n1r1 commented
/retest

2021-07-06 08:13 UTC, n1r1 commented
/retest

2021-07-06 08:14 UTC, n1r1 commented
/test ci/prow/test

2021-07-06 08:14 UTC, n1r1 commented
/test all

2021-07-06 08:49 UTC, n1r1 commented
/test all

2021-07-06 09:49 UTC, slintes reviewed
Thanks for the fast reviews!
Testing changes locally now before pushing to the PR

2021-07-06 09:49 UTC, slintes commented on e2e/poison_pill_test.go
> +				time.Sleep(time.Duration(reconnectInterval.Seconds()+10) * time.Second)
good idea 👍🏼

2021-07-06 09:49 UTC, slintes commented on e2e/poison_pill_test.go
> +				checkPPLogs(node, []string{"failed to check api server", "nodes couldn't access the api-server"})
checking logs is flaky already... would it add enough value?
when we get the response we expect here, I think we know already that the other node also worked as expected: it received the health request, and it replied with api error

2021-07-06 09:49 UTC, slintes commented on e2e/poison_pill_test.go
> +			Not(HaveOccurred()),
it is blocking, either because
- it returns the deadline exceeded error, but the timeout is long enough
- or because it succeeds

2021-07-06 09:49 UTC, slintes commented on e2e/poison_pill_test.go
> +	EventuallyWithOffset(1, func() types.UID {
hm, I think for this one I can remove Eventually indeed...

2021-07-06 09:49 UTC, slintes commented on e2e/poison_pill_test.go
> +	EventuallyWithOffset(1, func() time.Time {
... but here it is better, because executing the command might fail (reducing flakiness, as stated in the comment above)

2021-07-06 09:49 UTC, slintes commented on e2e/poison_pill_test.go
> +			return time.Time{}
done

2021-07-06 09:49 UTC, slintes commented on e2e/poison_pill_test.go
> +			return ""
done

2021-07-06 09:49 UTC, slintes commented on e2e/poison_pill_test.go
> +		Expect(logs).To(ContainSubstring(exp), "logs don t contain expected string, did the pod restart?")
fixed

2021-07-06 09:49 UTC, slintes commented on e2e/poison_pill_test.go
> +	oldPodUID := pod.GetUID()
done 👍🏼

2021-07-06 09:51 UTC, n1r1 commented on e2e/poison_pill_test.go
> +			})
makes sense, let's keep it as is

2021-07-06 09:54 UTC, n1r1 commented on e2e/poison_pill_test.go
> +						killApiConnection(&worker, apiIPs, true)
oh somehow I overlooked this :+1:

2021-07-06 09:56 UTC, n1r1 commented on e2e/poison_pill_test.go
> +				checkPPLogs(node, []string{"failed to check api server", "nodes couldn't access the api-server"})
let's start with adding just the first two checks which don't rely on log.
the added value is:

1. more coverage. testing the other node is also important
2. this might help to understand why test fail (e.g. the peer was rebooted while the node asks for health status)

2021-07-06 14:53 UTC, n1r1 commented
/lgtm

2021-07-06 14:59 UTC, n1r1 commented
/override Codacy Static Code Analysis

2021-07-06 15:00 UTC, merged